width : 1024
height : 64
fov_up : 5.0
fov_down : -23.0
p_stable : 0.6
p_prior : 0.5
sigma_angle : 1.0
sigma_distance : 1.0
angle_thred : 45.0
distance_thred : 1
gamma : 0.5
confidence_threshold : 0.0
time_gap : 2
inactive_time : 100
skip_gap : 0
loop_thred : 3
max_distance_gap : 0.1
max_angle_gap : 0.01
pcdpath : /home/tongda/workspace/semantic_map/dataset/pcd_data/05/
render_gap : 500
model_path : /home/tongda/workspace/semantic_map/catkin_ws/src/rangenet_lib/darknet53
pose_path : /home/tongda/workspace/semantic_map/smros_catkin_ws/src/smros/pose_result/pose_05.txt
loop_result : /home/tongda/workspace/semantic_map/loop_result.txt